In [2]:
import pandas as pd

In [48]:
inp=pd.read_csv("/Users/moradigd/Documents/Hostsp/combined",delim_whitespace=True,index_col=0)

In [49]:
inp_transposed=inp.T

In [50]:
inp_transposed.shape

(1490, 737401)

In [92]:
from scipy.sparse import csr_matrix
import numpy as np
import pandas as pd

matrix = csr_matrix(inp_transposed.to_numpy(), dtype=np.int8)

In [99]:
df = pd.DataFrame.sparse.from_spmatrix(matrix, index=inp_transposed.columns)

ValueError: Index length mismatch: 737401 vs. 1490

In [94]:
df.sparse.to_dense()

POS   11       17       22       26       40       55       58       64       \
0           0        0        0        0        0        0        0        0   
1           0        0        0        0        0        0        0        0   
2           0        0        0        0        0        0        0        0   
3           0        0        0        0        0        0        0        0   
4           0        0        0        0        0        0        0        0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
1485        0        0        0        0        0        0        0        0   
1486        0        0        0        0        0        0        0        0   
1487        0        0        1        0        0        0        1        1   
1488        0        0        1        0        0        0        1        1   
1489        0        0        0        0        0        0        1        1   

POS   68       69       ...  4641553  4641568  4641574  4641577  4641589  \
0           0        0  ...        0        0        0        0        0   
1           0        0  ...        0        0        0        0        0   
2           0        0  ...        0        0        0        0        0   
3           0        0  ...        0        0        0        0        0   
4           0        0  ...        0        0        0        0        0   
...       ...      ...  ...      ...      ...      ...      ...      ...   
1485        0        0  ...        0        0        0        0        0   
1486        0        0  ...        0        0        0        0        0   
1487        0        0  ...        0        0        0        0        0   
1488        0        0  ...        0        0        0        0        0   
1489        0        0  ...        0        0        0        0        0   

POS   4641622  4641634  4641635  4641638  4641639  
0           0        0        0        0        0  
1           0        0        0        0        0  
2           0        0        0        0        0  
3           0        0        0        0        0  
4           0        0        0        0        0  
...       ...      ...      ...      ...      ...  
1485        0        0        0        0        0  
1486        0        0        0        0        0  
1487        0        0        0        0        0  
1488        0        0        0        0        0  
1489        0        0        0        0        0  

[1490 rows x 737401 columns]

In [5]:
from scipy import sparse

#sparse.save_npz("/Users/moradigd/Documents/Hostsp/sparse_inp.npz", matrix)


In [6]:
#pd.DataFrame.sparse.from_spmatrix(your_matrix_back, columns=inp_transposed.columns)
your_matrix_back = sparse.load_npz("/Users/moradigd/Documents/Hostsp/sparse_inp.npz")

In [26]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(inp.iloc[:,1].to_list())
le.transform(inp.iloc[:,1].to_list())

array([1, 1, 2, ..., 0, 2, 1])

In [44]:
inp.iloc[:,1].to_list()

['CLENV',
 'CLENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'CLCL',
 'CLCL',
 'CLCL',
 'CLENV',
 'CLENV',
 'CLCL',
 'CLENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'CLCL',
 'CLENV',
 'CLCL',
 'CLENV',
 'CLENV',
 'CLCL',
 'CLENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'CLENV',
 'ENVENV',
 'ENVENV',
 'CLENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'ENVENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'ENVENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'ENVENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'CLENV',
 'ENVENV',
 'ENVENV',
 'CLENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'ENVENV',
 'CLENV',
 'EN

In [27]:
#inp.iloc[:,1].to_list()
#le.fit(inp.iloc[:,1].to_list())
le.transform(["tokyo", "tokyo", "paris"])

ValueError: y contains previously unseen labels: ['paris', 'tokyo']

In [28]:
xgtrain = xgb.DMatrix(your_matrix_back, label = le.transform(inp.iloc[:,1].to_list()))

In [101]:
pd.DataFrame.sparse.from_spmatrix(your_matrix_back, index=inp_transposed.index)

0       1       2       3       4       5       6       7       \
modified_ids                                                                   
ERR1055872         0       0       0       0       0       0       0       0   
ERR1055887         0       0       0       0       0       0       0       0   
ERR1055898         0       0       0       0       0       0       0       0   
ERR1055906         0       0       0       0       0       0       0       0   
ERR1100489         0       0       0       0       0       0       0       0   
...              ...     ...     ...     ...     ...     ...     ...     ...   
SRR9984938         0       0       0       0       0       0       0       0   
SRR9987785         0       0       0       0       0       0       0       0   
SRR9988120         0       0       1       0       0       0       1       1   
SRR9997746         0       0       1       0       0       0       1       1   
SRR9998315         0       0       0       0       0       0       1       1   

              8       9       ...  737391  737392  737393  737394  737395  \
modified_ids                  ...                                           
ERR1055872         0       0  ...       0       0       0       0       0   
ERR1055887         0       0  ...       0       0       0       0       0   
ERR1055898         0       0  ...       0       0       0       0       0   
ERR1055906         0       0  ...       0       0       0       0       0   
ERR1100489         0       0  ...       0       0       0       0       0   
...              ...     ...  ...     ...     ...     ...     ...     ...   
SRR9984938         0       0  ...       0       0       0       0       0   
SRR9987785         0       0  ...       0       0       0       0       0   
SRR9988120         0       0  ...       0       0       0       0       0   
SRR9997746         0       0  ...       0       0       0       0       0   
SRR9998315         0       0  ...       0       0       0       0       0   

              737396  737397  737398  737399  737400  
modified_ids                                          
ERR1055872         0       0       0       0       0  
ERR1055887         0       0       0       0       0  
ERR1055898         0       0       0       0       0  
ERR1055906         0       0       0       0       0  
ERR1100489         0       0       0       0       0  
...              ...     ...     ...     ...     ...  
SRR9984938         0       0       0       0       0  
SRR9987785         0       0       0       0       0  
SRR9988120         0       0       0       0       0  
SRR9997746         0       0       0       0       0  
SRR9998315         0       0       0       0       0  

[1490 rows x 737401 columns]

In [ ]:
xgTrain = xgb.DMatrix(X, label=y)
cvresult = xgb.cv(xgbParams,
                      xgTrain,
                      num_boost_round=alg.get_params()['n_estimators'],
                      nfold=cvFolds,
                      stratified=True,
                      metrics={'mlogloss'},
                      early_stopping_rounds=early_stopping_rounds,
                      seed=0,
                      callbacks=[xgb.callback.print_evaluation(show_stdv=False),                                                               xgb.callback.early_stop(3)])

print cvresult
alg.set_params(n_estimators=cvresult.shape[0])

    # Fit the algorithm
alg.fit(X, y, eval_metric='mlogloss')

    # Predict
dtrainPredictions = alg.predict(X)
dtrainPredProb = alg.predict_proba(X)

In [2]:
import numpy as np
import pandas as pd
import xgboost as xgb
from xgboost.sklearn import  XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import  metrics
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV, train_test_split
from sklearn.model_selection import cross_validate

In [39]:
X_csr=your_matrix_back
y= le.transform(inp.iloc[:,1].to_list())
X_train, X_test, y_train, y_test = train_test_split(X_csr, y, test_size=0.33, random_state=42)

In [40]:
xgb1 = xgb.XGBClassifier()

xgb1.fit(X_train, y_train)


[18:23:50] WARNING: /private/var/folders/nv/6yj1fb6n7dzd2sbzwdp7ghxwqcvt45/T/pip-install-1ukgzm4y/xgboost/build/temp.macosx-10.9-x86_64-3.8/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [41]:
pred=xgb1.predict(X_test)

In [34]:
ids=pd.read_csv("/Users/moradigd/Documents/Hostsp/labels_new.csv",index_col=0)

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[173,  25,  14],
       [ 97,  38,  29],
       [  7,  13,  96]])

In [38]:
ids.loc[inp_transposed.index,:]

NameError: name 'inp_transposed' is not defined

In [70]:
inp_transposed.index

Index(['ERR1055872', 'ERR1055887', 'ERR1055898', 'ERR1055906', 'ERR1100489',
       'ERR1156342', 'ERR1195614', 'ERR1195649', 'ERR1204093', 'ERR1204101',
       ...
       'SRR9984737', 'SRR9984758', 'SRR9984791', 'SRR9984795', 'SRR9984854',
       'SRR9984938', 'SRR9987785', 'SRR9988120', 'SRR9997746', 'SRR9998315'],
      dtype='object', length=1490)

In [71]:
ids.index

Index(['SRR9092785', 'SRR9998254', 'SRR9997746', 'SRR9990116', 'SRR9987785',
       'SRR9984938', 'SRR9984854', 'SRR9984795', 'SRR9984795', 'SRR9984791',
       ...
       'ERR1543423', 'ERR1423312', 'ERR135835', 'ERR1218679', 'ERR1218545',
       'ERR1204986', 'ERR1195614', 'ERR1163820', 'ERR1055887', 'ERR1055872'],
      dtype='object', name='id', length=2134)

In [72]:
ids.index.isin(inp_transposed.index)

array([ True, False,  True, ..., False,  True,  True])

In [88]:
ids[ids.index.isin(inp_transposed.index)].iloc[:,0]

ids
ERR1055872    ERR1055872
ERR1055887    ERR1055887
ERR1055898    ERR1055898
ERR1055906    ERR1055906
ERR1100489    ERR1100489
                 ...    
SRR9984938    SRR9984938
SRR9987785    SRR9987785
SRR9988120    SRR9988120
SRR9997746    SRR9997746
SRR9998315    SRR9998315
Name: modified_ids, Length: 1490, dtype: object

In [89]:
inp_transposed.index=ids[ids.index.isin(inp_transposed.index)].iloc[:,0]

In [102]:
pd.DataFrame(inp_transposed.columns).to_csv("/Users/moradigd/Documents/Hostsp/columns_corrected.csv")

In [11]:
import pandas as pd
#inp=pd.read_csv("/Users/moradigd/Documents/Hostsp/combined_corrected.csv",index_col=0)
inp=pd.read_csv("/Users/moradigd/Documents/Hostsp/labels_new.csv",index_col=0)
inp.iloc[:,1].to_numpy()

array(['CLENV', 'CLENV', 'ENVENV', ..., 'CLCL', 'ENVENV', 'CLENV'],
      dtype=object)